### PR TITLE
Add CMake support.

### PR DESCRIPTION
**Pull request by susilehtola**
This pull request adds a simple CMake file that can be used to build packmol.

### CODE REVIEW

**Comment by leandromartinez98** [comment]
Thank you for your support. Can you briefly explain why is this useful? Does it interfere with the current make protocol?

**Comment by susilehtola** [comment]
Sure. The point about CMake is that it's way easier to use than old makefiles. It can do out-of-root builds, and automatically handles dependencies in the sources. For example, most of the existing Makefile consists of manual tracking of the dependencies, which isn't necessary in CMake.

On my computer building the project using the old makefile takes 7.5 seconds, while the CMake build takes only 2 seconds, both run with
$ make -j

The CMake file can coexist with the old makefile. I've now added a script to demonstrate how to build the project using CMake.

**Comment by leandromartinez98** [comment]
Ok, thank you. Merged.

**Comment by leandromartinez98** [comment]
At the same time, apparently it is trying to copy the binary file to /bin. In that case, the user needs root privileges to run the script. Is that what you want? Currently the binary is generated simply within the packmol directory.

**Comment by susilehtola** [comment]
Actually, the compile script was missing one line - the installation target should be bin/ by default. I'll prepare another PR to fix this.

**Comment by susilehtola** [comment]
But, using the compile script is totally optional - CMake can be run manually as well, the script is just there as an example on how to set the compiler and compiler flags, the target directory etc.

**Pull request merged**
